spring:
  application:
    name: agency

  # Disable DevTools auto-restart to prevent duplicate Spring Bean loading
  devtools:
    restart:
      enabled: false

  #security settings
  security:
    user:
      name: admin #test-account
      password: admin123
      roles: ADMIN

  profiles:
    active: local   #default profile

  #db settings
  datasource:
    driver-class-name: org.h2.Driver #temp db
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  #springdoc swagger settings
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  #webview settings
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  thymeleaf:
    cache: false    # 개발 중엔 false (prod에서 true로 오버라이드)

  #mybatis settings
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
      jdbc-type-for-null: null

  #jpa settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

#server settings
server:
  port: 8082

#jwt settings
jwt:
  secret: MySecretKeyForJWTTokenGenerationAndValidationPurpose12345
  expiration: 1800000

#log settings
logging:
  level:
    root: INFO
    org.springframework.web: INFO